name: flutter_bloc_provider
description: This package provides tools to easily implement the bloc pattern.
version: 1.0.0
homepage: https://github.com/Dev-hwang/flutter_bloc_provider

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
